### ISSUE TITLE
Remove TODO's

### ISSUE THREAD

**Issue by eshu0** [elecfreaks/pxt-TPBot#2]
in the main.ts the "TODO" is in the comments this shows up in makecode javascript view and makes it look like the solution is not complete.
The comment has actually been written correctly.

For example the following comment:
TODO: Set the speed of left and right wheels

Should just be:
Set the speed of left and right wheels

If you remove these it will look better - hope this helps.

**Comment by lionyhw** [comment]
Yes, we will fix it as soon as possible.
